dependencies {
    implementation project(':common:security-jwt')
    implementation 'io.livekit:livekit-server:0.12.1'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb-reactive'
}

tasks.register("prepareKotlinBuildScriptModel"){}

bootJar {
    enabled = true
}

jar{
    enabled = false
}