dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation(project(':modules:user:user-core'))
    implementation(project(':modules:seller:seller-core'))
    implementation(project(':storage:db-core'))
    implementation(project(':common:global'))
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-batch-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.register("prepareKotlinBuildScriptModel"){}

bootJar {
    enabled = true
}

// architecture-test가 batchapp 클래스를 분석하려면 plain jar 필요 (bootJar는 BOOT-INF 구조라 분석 불가)
jar{
    enabled = true
}
