dependencies {
    implementation(project(':modules:notification:notification-api'))

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'com.solapi:sdk:1.0.3'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.register("prepareKotlinBuildScriptModel"){}
