dependencies {
    implementation(project(':common:core'))
    implementation(project(':common:web'))
    implementation(project(':modules:seller:seller-api'))
    implementation(project(':modules:user:user-api'))
    implementation(project(':storage:db-core'))

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.security:spring-security-core'
    implementation 'org.springframework:spring-web'
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'

    annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
}

tasks.register("prepareKotlinBuildScriptModel"){}
