-- product 도메인 초기 스키마 (카탈로그·옵션·가격·문의·랭킹/검색·outbox/audit — review는 review_schema로 분리)
-- 출처: erd-dbdiagram.io-final-add-live.md (§2 카테고리 · §3 옵션 속성 템플릿 · §4 상품 · §5 상품 옵션
--       · §6 기간 할인 + 승자 캐시 · §13 상품 Q&A · §19 운영(베스트/감사) · §20 검색 로그 · §31 Outbox)
-- 규칙:
--   * 물리 FK 미사용 (도메인 간/내부 모두). 참조는 uuid/bigint id 컬럼으로만 표현.
--   * bigint PK: categories는 IDENTITY(DB 자동생성, LongTimeEntity 매핑); 검색로그·통계·outbox는
--     앱 생성 TSID(serial 미사용, 배치 COPY 호환) — INSERT 시 앱이 id 주입.
--   * uuid PK는 앱 생성 UUIDv7 권장, gen_random_uuid()는 fallback 기본값.
--   * 검색 로그/통계는 비파티션 단순 테이블 (월별 RANGE 파티셔닝은 운영 단계에서 적용).
CREATE SCHEMA IF NOT EXISTS product_schema;

-- categories.path 용 ltree 확장 (DB당 1회. flyway_role에 권한 없으면 DBA가 사전 생성)
CREATE EXTENSION IF NOT EXISTS ltree;

-- ============================================================
-- §2  카테고리 (ltree)
-- ============================================================

-- 상품 카테고리 트리 (ltree, depth 최대 4). id는 ltree 라벨로 직접 사용 → bigint
CREATE TABLE product_schema.categories
(
    id         bigint       GENERATED BY DEFAULT AS IDENTITY, -- DB 자동생성. ltree 라벨로 직접 사용
    parent_id  bigint,                -- self ref (NULL=최상위)
    path       ltree        NOT NULL, -- 라벨=id 숫자 그대로 (예: 1042.3851.7720)
    name       varchar(100) NOT NULL,
    depth      smallint     NOT NULL, -- 깊이 (1~4), nlevel(path) 캐시
    sort_order integer      NOT NULL DEFAULT 0,
    is_active  boolean      NOT NULL DEFAULT true,
    created_at timestamptz  NOT NULL,
    updated_at timestamptz  NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);
CREATE INDEX ON product_schema.categories USING GIST (path);
CREATE INDEX ON product_schema.categories (parent_id, sort_order);
CREATE INDEX ON product_schema.categories (depth, is_active, sort_order);

COMMENT ON TABLE product_schema.categories IS '상품 카테고리 트리 (ltree, depth 최대 4)';
COMMENT ON COLUMN product_schema.categories.id IS 'PK — bigint IDENTITY(DB 자동생성). ltree 라벨로 직접 사용';
COMMENT ON COLUMN product_schema.categories.parent_id IS '상위 카테고리 id (NULL=최상위)';
COMMENT ON COLUMN product_schema.categories.path IS 'ltree 경로. 라벨=id 숫자 그대로. GiST 인덱스로 서브트리/조상 조회';
COMMENT ON COLUMN product_schema.categories.name IS '카테고리명';
COMMENT ON COLUMN product_schema.categories.depth IS '깊이 (1~4), nlevel(path) 캐시';
COMMENT ON COLUMN product_schema.categories.sort_order IS '동일 부모 내 노출 순서';
COMMENT ON COLUMN product_schema.categories.is_active IS '노출 여부';

-- ============================================================
-- §3  옵션 속성 템플릿
-- ============================================================

-- 옵션 속성 그룹 템플릿. 관리자 공용 + 판매자 커스텀 구분
CREATE TABLE product_schema.option_attribute_groups
(
    id          uuid        NOT NULL DEFAULT gen_random_uuid(),
    name        varchar(50) NOT NULL, -- 예: 색상, 사이즈, RAM
    is_system   boolean     NOT NULL DEFAULT true, -- true=관리자 공용, false=판매자 커스텀
    seller_id   uuid, -- ref: users.id (커스텀 생성 판매자, 시스템은 NULL)
    description varchar(255),
    created_at  timestamptz NOT NULL,
    updated_at  timestamptz NOT NULL,
    CONSTRAINT pk_option_attribute_groups PRIMARY KEY (id)
);
CREATE INDEX ON product_schema.option_attribute_groups (is_system);
CREATE INDEX ON product_schema.option_attribute_groups (seller_id);

COMMENT ON TABLE product_schema.option_attribute_groups IS '옵션 속성 그룹 템플릿. 관리자 공용 + 판매자 커스텀 구분';
COMMENT ON COLUMN product_schema.option_attribute_groups.name IS '속성 그룹명 (예: 색상, 사이즈, RAM)';
COMMENT ON COLUMN product_schema.option_attribute_groups.is_system IS 'true=관리자 공용, false=판매자 커스텀';
COMMENT ON COLUMN product_schema.option_attribute_groups.seller_id IS 'ref: users.id (커스텀 생성 판매자, 시스템은 NULL)';
COMMENT ON COLUMN product_schema.option_attribute_groups.description IS '그룹 설명';

-- 속성 그룹별 사전 정의 값 목록 (드롭박스 선택지)
CREATE TABLE product_schema.option_attribute_group_presets
(
    id                 uuid         NOT NULL DEFAULT gen_random_uuid(),
    attribute_group_id uuid         NOT NULL, -- ref: option_attribute_groups.id
    value              varchar(100) NOT NULL, -- 예: 빨강, M, 16GB
    sort_order         integer      NOT NULL DEFAULT 0,
    created_at         timestamptz  NOT NULL,
    CONSTRAINT pk_option_attribute_group_presets PRIMARY KEY (id)
);
CREATE INDEX ON product_schema.option_attribute_group_presets (attribute_group_id, sort_order);

COMMENT ON TABLE product_schema.option_attribute_group_presets IS '속성 그룹별 사전 정의 값 목록 (드롭박스 선택지)';
COMMENT ON COLUMN product_schema.option_attribute_group_presets.attribute_group_id IS 'ref: option_attribute_groups.id';
COMMENT ON COLUMN product_schema.option_attribute_group_presets.value IS '사전 정의 값 (예: 빨강, M, 16GB)';
COMMENT ON COLUMN product_schema.option_attribute_group_presets.sort_order IS '드롭박스 노출 순서';

-- 카테고리별 권장 속성 그룹 매핑. 판매자 옵션 등록 화면 드롭박스 소스
CREATE TABLE product_schema.category_option_attribute_groups
(
    id                 uuid        NOT NULL DEFAULT gen_random_uuid(),
    category_id        bigint      NOT NULL, -- ref: categories.id
    attribute_group_id uuid        NOT NULL, -- ref: option_attribute_groups.id
    sort_order         integer     NOT NULL DEFAULT 0,
    created_at         timestamptz NOT NULL,
    CONSTRAINT pk_category_option_attribute_groups PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ON product_schema.category_option_attribute_groups (category_id, attribute_group_id);
CREATE INDEX ON product_schema.category_option_attribute_groups (category_id, sort_order);

COMMENT ON TABLE product_schema.category_option_attribute_groups IS '카테고리별 권장 속성 그룹 매핑. 판매자 옵션 등록 화면 드롭박스 소스';
COMMENT ON COLUMN product_schema.category_option_attribute_groups.category_id IS 'ref: categories.id';
COMMENT ON COLUMN product_schema.category_option_attribute_groups.attribute_group_id IS 'ref: option_attribute_groups.id';
COMMENT ON COLUMN product_schema.category_option_attribute_groups.sort_order IS '드롭박스 노출 순서';

-- ============================================================
-- §4  상품
-- ============================================================

-- 상품 원장. 정렬·필터용 캐시 컬럼은 앱이 갱신 책임
CREATE TABLE product_schema.products
(
    id                      uuid          NOT NULL DEFAULT gen_random_uuid(),
    seller_id               uuid          NOT NULL, -- ref: users.id
    category_id             bigint        NOT NULL, -- ref: categories.id
    name                    varchar(255)  NOT NULL,
    description             text,                   -- 상세 설명 (최대 30,000자)
    base_price              integer       NOT NULL, -- 목록 표시용 시작 가격
    status                  varchar(20)   NOT NULL DEFAULT 'PENDING_REVIEW', -- ENUM: PENDING_REVIEW, ON_SALE, SUSPENDED, REJECTED
    shipping_policy_id      uuid,                   -- ref: seller_shipping_policies.id (NULL=판매자 기본 정책)
    additional_shipping_fee integer       NOT NULL DEFAULT 0, -- 상품 단독 배송비. 0 초과 시 판매자 정책 무시
    rejection_reason        text,                   -- 검수 반려 사유
    deleted_at              timestamptz,            -- 논리 삭제 일시
    min_price               integer,                -- 할인 후 최저 조합 가격. NULL=재고 조합 없음. 앱이 갱신
    has_stock               boolean       NOT NULL DEFAULT true, -- 재고 있는 조합 존재 여부. 앱이 갱신
    purchase_count          integer       NOT NULL DEFAULT 0, -- 누적 구매 완료 수 (구매인기순)
    avg_rating              numeric(3, 1),          -- 평균 별점 캐시. NULL=리뷰 없음
    review_count            integer       NOT NULL DEFAULT 0,
    view_count              integer       NOT NULL DEFAULT 0, -- 상품 상세 조회 수 (Redis 버퍼링 후 반영)
    wishlist_count          integer       NOT NULL DEFAULT 0,
    option_model            varchar(20)   NOT NULL DEFAULT 'COMBINATION', -- ENUM: COMBINATION, COMPONENT, HYBRID
    search_indexed_at       timestamptz,            -- ES 마지막 인덱싱 일시
    created_at              timestamptz   NOT NULL,
    updated_at              timestamptz   NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);
CREATE INDEX ON product_schema.products (seller_id, status, deleted_at);
CREATE INDEX ON product_schema.products (category_id, status, deleted_at);
CREATE INDEX ON product_schema.products (status, deleted_at, min_price);      -- 가격순 정렬
CREATE INDEX ON product_schema.products (status, deleted_at, purchase_count); -- 인기순 정렬 (구매수)
CREATE INDEX ON product_schema.products (status, deleted_at, avg_rating);     -- 별점순 정렬
CREATE INDEX ON product_schema.products (status, deleted_at, wishlist_count); -- 찜순 정렬
CREATE INDEX ON product_schema.products (status, deleted_at, view_count);     -- 조회순 정렬
CREATE INDEX ON product_schema.products (status, created_at);
CREATE INDEX ON product_schema.products (shipping_policy_id);
CREATE INDEX ON product_schema.products (option_model);
CREATE INDEX ON product_schema.products (search_indexed_at)
    WHERE search_indexed_at IS NULL OR search_indexed_at < updated_at;        -- stale 후보

COMMENT ON TABLE product_schema.products IS '상품 원장. 정렬·필터용 캐시 컬럼(min_price·has_stock·purchase_count·avg_rating·review_count·view_count·wishlist_count)은 앱이 갱신 책임';
COMMENT ON COLUMN product_schema.products.seller_id IS 'ref: users.id';
COMMENT ON COLUMN product_schema.products.category_id IS 'ref: categories.id';
COMMENT ON COLUMN product_schema.products.description IS '상세 설명 (최대 30,000자)';
COMMENT ON COLUMN product_schema.products.base_price IS '목록 표시용 시작 가격. 옵션 없는 상품은 결제 금액과 동일';
COMMENT ON COLUMN product_schema.products.status IS 'ENUM: PENDING_REVIEW, ON_SALE, SUSPENDED, REJECTED. 삭제는 deleted_at으로 처리';
COMMENT ON COLUMN product_schema.products.shipping_policy_id IS 'ref: seller_shipping_policies.id. NULL=판매자 기본 정책 적용';
COMMENT ON COLUMN product_schema.products.additional_shipping_fee IS '상품 단독 배송비. 0 초과 시 판매자 정책 무시하고 이 금액만 적용';
COMMENT ON COLUMN product_schema.products.rejection_reason IS '검수 반려 사유';
COMMENT ON COLUMN product_schema.products.deleted_at IS '논리 삭제 일시';
COMMENT ON COLUMN product_schema.products.min_price IS '할인 후 최저 조합 가격 = MIN(COALESCE(cwd.final_price, poc.price)). NULL=재고 조합 없음. 앱이 갱신. 라이브 특별가 미반영';
COMMENT ON COLUMN product_schema.products.has_stock IS '재고 있는 조합 존재 여부 = EXISTS((stock - reserved_stock) > 0 AND is_available). 앱이 갱신';
COMMENT ON COLUMN product_schema.products.purchase_count IS '누적 구매 완료 수 (구매인기순). deliveries.status=DELIVERED 전환 시 +1';
COMMENT ON COLUMN product_schema.products.avg_rating IS '평균 별점 캐시. NULL=리뷰 없음. review 변경 시 갱신';
COMMENT ON COLUMN product_schema.products.review_count IS '리뷰 수 캐시';
COMMENT ON COLUMN product_schema.products.view_count IS '상품 상세 조회 수 (조회순 정렬). Redis 버퍼링 후 반영';
COMMENT ON COLUMN product_schema.products.wishlist_count IS '찜 수 캐시 (찜순 정렬). wishlists 추가/취소 시 앱이 갱신';
COMMENT ON COLUMN product_schema.products.option_model IS 'ENUM: COMBINATION, COMPONENT, HYBRID. 현재 COMBINATION 고정';
COMMENT ON COLUMN product_schema.products.search_indexed_at IS 'ES 마지막 인덱싱 일시. 동기화 lag 모니터링';

-- 상품 태그. 검색·기획전 필터용. 상품당 최대 10개
CREATE TABLE product_schema.product_tags
(
    id         uuid        NOT NULL DEFAULT gen_random_uuid(),
    product_id uuid        NOT NULL, -- ref: products.id
    name       varchar(20) NOT NULL, -- 최대 20자, 특수문자 불허
    created_at timestamptz NOT NULL,
    CONSTRAINT pk_product_tags PRIMARY KEY (id)
);
CREATE INDEX ON product_schema.product_tags (product_id);
CREATE INDEX ON product_schema.product_tags (name);

COMMENT ON TABLE product_schema.product_tags IS '상품 태그. 검색·기획전 필터용. 상품당 최대 10개';
COMMENT ON COLUMN product_schema.product_tags.product_id IS 'ref: products.id';
COMMENT ON COLUMN product_schema.product_tags.name IS '태그명. 최대 20자, 특수문자 불허';

-- 판매자가 묶은 관련 상품 그룹. 기획전 구성 등 용도
CREATE TABLE product_schema.product_group_sets
(
    id         uuid        NOT NULL DEFAULT gen_random_uuid(),
    seller_id  uuid        NOT NULL, -- ref: users.id
    group_name varchar(255),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT pk_product_group_sets PRIMARY KEY (id)
);

COMMENT ON TABLE product_schema.product_group_sets IS '판매자가 묶은 관련 상품 그룹. 기획전 구성 등 용도';
COMMENT ON COLUMN product_schema.product_group_sets.seller_id IS 'ref: users.id';
COMMENT ON COLUMN product_schema.product_group_sets.group_name IS '관련 상품 그룹명';

-- 상품 그룹 구성 아이템. 노출 순서 관리
CREATE TABLE product_schema.product_group_items
(
    id           uuid        NOT NULL DEFAULT gen_random_uuid(),
    group_set_id uuid        NOT NULL, -- ref: product_group_sets.id
    product_id   uuid        NOT NULL, -- ref: products.id
    sort_order   integer     NOT NULL DEFAULT 0,
    created_at   timestamptz NOT NULL,
    CONSTRAINT pk_product_group_items PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ON product_schema.product_group_items (group_set_id, product_id);
CREATE INDEX ON product_schema.product_group_items (product_id);

COMMENT ON TABLE product_schema.product_group_items IS '상품 그룹 구성 아이템. 노출 순서 관리';
COMMENT ON COLUMN product_schema.product_group_items.group_set_id IS 'ref: product_group_sets.id';
COMMENT ON COLUMN product_schema.product_group_items.product_id IS 'ref: products.id';
COMMENT ON COLUMN product_schema.product_group_items.sort_order IS '노출 순서';

-- 상품·옵션 이미지 통합(폴리모픽). 소유자=상품(공유) XOR 옵션값(색상별)
CREATE TABLE product_schema.product_images
(
    id              uuid         NOT NULL DEFAULT gen_random_uuid(),
    product_id      uuid,                       -- ref: products.id. 기본(공유) 이미지 소유
    option_value_id uuid,                       -- ref: product_option_values.id (주로 색상). 옵션값 종속 이미지
    image_role      varchar(10)  NOT NULL,      -- ENUM: GALLERY(대표 ≤5), DETAIL(상세 ≤10), BODY(본문 인라인), SWATCH(색칩)
    image_key       varchar(500) NOT NULL,
    sort_order      smallint     NOT NULL DEFAULT 0,
    created_at      timestamptz  NOT NULL,
    CONSTRAINT pk_product_images PRIMARY KEY (id),
    CONSTRAINT ck_product_images_owner CHECK ((product_id IS NULL) <> (option_value_id IS NULL)),
    CONSTRAINT ck_product_images_swatch CHECK (image_role <> 'SWATCH' OR option_value_id IS NOT NULL),
    CONSTRAINT ck_product_images_body CHECK (image_role <> 'BODY' OR product_id IS NOT NULL)
);
CREATE INDEX ON product_schema.product_images (product_id, image_role, sort_order);
CREATE INDEX ON product_schema.product_images (option_value_id, image_role, sort_order);
-- 옵션값당 색칩 1개
CREATE UNIQUE INDEX ON product_schema.product_images (option_value_id) WHERE image_role = 'SWATCH';

COMMENT ON TABLE product_schema.product_images IS '상품·옵션 이미지 통합(폴리모픽). 소유자=상품(공유) XOR 옵션값(색상별). 색상 선택 시 GALLERY·DETAIL은 해당 옵션값 이미지로 오버라이드(없으면 상품 공유 폴백), BODY는 항상 상품 공유, SWATCH는 색칩. 개수 상한(대표 5/상세 10)은 앱 강제';
COMMENT ON COLUMN product_schema.product_images.product_id IS 'ref: products.id. 기본(공유) 이미지 소유. option_value_id와 정확히 하나만 NOT NULL';
COMMENT ON COLUMN product_schema.product_images.option_value_id IS 'ref: product_option_values.id (주로 색상). 옵션값 종속 이미지 — 선택 시 기본 오버라이드';
COMMENT ON COLUMN product_schema.product_images.image_role IS 'ENUM: GALLERY(대표 ≤5), DETAIL(상세 ≤10), BODY(본문 인라인), SWATCH(색칩)';
COMMENT ON COLUMN product_schema.product_images.image_key IS '스토리지 키';
COMMENT ON COLUMN product_schema.product_images.sort_order IS 'GALLERY/DETAIL 노출 순서. BODY는 본문 HTML 내 위치가 순서이므로 0. SWATCH는 값당 1개';

-- ============================================================
-- §5  상품 옵션
-- ============================================================

-- 상품별 옵션 타입 (색상, 사이즈 등). 계층 순서로 드롭박스 선택 흐름 결정
CREATE TABLE product_schema.product_option_types
(
    id                 uuid        NOT NULL DEFAULT gen_random_uuid(),
    product_id         uuid        NOT NULL, -- ref: products.id
    attribute_group_id uuid,                 -- ref: option_attribute_groups.id (NULL=완전 커스텀)
    name               varchar(50) NOT NULL, -- 그룹 선택 시 복사, 커스텀 시 직접 입력
    sort_order         smallint    NOT NULL, -- 옵션 선택 계층 순서 (1=최상위)
    deleted_at         timestamptz,          -- 논리 삭제 일시
    created_at         timestamptz NOT NULL,
    updated_at         timestamptz NOT NULL,
    CONSTRAINT pk_product_option_types PRIMARY KEY (id)
);
CREATE INDEX ON product_schema.product_option_types (product_id, sort_order);
CREATE INDEX ON product_schema.product_option_types (attribute_group_id);
-- 옵션 타입명 중복 방지
CREATE UNIQUE INDEX ON product_schema.product_option_types (product_id, name) WHERE deleted_at IS NULL;

COMMENT ON TABLE product_schema.product_option_types IS '상품별 옵션 타입 (색상, 사이즈 등). 계층 순서로 드롭박스 선택 흐름 결정';
COMMENT ON COLUMN product_schema.product_option_types.product_id IS 'ref: products.id';
COMMENT ON COLUMN product_schema.product_option_types.attribute_group_id IS 'ref: option_attribute_groups.id (NULL=완전 커스텀)';
COMMENT ON COLUMN product_schema.product_option_types.name IS '타입명 — 그룹 선택 시 복사, 커스텀 시 직접 입력';
COMMENT ON COLUMN product_schema.product_option_types.sort_order IS '옵션 선택 계층 순서 (1=최상위)';
COMMENT ON COLUMN product_schema.product_option_types.deleted_at IS '논리 삭제 일시';

-- 옵션 타입별 선택 값 (빨강, M 등). 프리셋 또는 직접 입력
CREATE TABLE product_schema.product_option_values
(
    id                  uuid         NOT NULL DEFAULT gen_random_uuid(),
    option_type_id      uuid         NOT NULL, -- ref: product_option_types.id
    attribute_preset_id uuid,                  -- ref: option_attribute_group_presets.id (NULL=직접 입력)
    value               varchar(100) NOT NULL, -- 프리셋 선택 시 복사, 커스텀 시 입력
    metadata            jsonb,                 -- 확장 메타데이터. 예: {"hex":"#FF0000"}
    price_delta         integer      NOT NULL DEFAULT 0, -- 옵션값별 가격 가산액(원)
    sort_order          smallint     NOT NULL,
    deleted_at          timestamptz,           -- 논리 삭제 일시
    created_at          timestamptz  NOT NULL,
    updated_at          timestamptz  NOT NULL,
    CONSTRAINT pk_product_option_values PRIMARY KEY (id)
);
CREATE INDEX ON product_schema.product_option_values (option_type_id, sort_order);
-- 옵션값 중복 방지
CREATE UNIQUE INDEX ON product_schema.product_option_values (option_type_id, value) WHERE deleted_at IS NULL;

COMMENT ON TABLE product_schema.product_option_values IS '옵션 타입별 선택 값 (빨강, M 등). 프리셋 또는 직접 입력';
COMMENT ON COLUMN product_schema.product_option_values.option_type_id IS 'ref: product_option_types.id';
COMMENT ON COLUMN product_schema.product_option_values.attribute_preset_id IS 'ref: option_attribute_group_presets.id (NULL=직접 입력)';
COMMENT ON COLUMN product_schema.product_option_values.value IS '옵션 값 — 프리셋 선택 시 복사, 커스텀 시 입력';
COMMENT ON COLUMN product_schema.product_option_values.metadata IS '확장 메타데이터. 예: {"hex":"#FF0000"}. NULL=없음';
COMMENT ON COLUMN product_schema.product_option_values.price_delta IS '옵션값별 가격 가산액(원). 조합 생성 시 combination.price = base_price + Σ(price_delta)에 사용. 0=가격 영향 없음';
COMMENT ON COLUMN product_schema.product_option_values.sort_order IS '노출 순서';
COMMENT ON COLUMN product_schema.product_option_values.deleted_at IS '논리 삭제 일시';

-- 옵션 조합별 재고·가격·SKU 관리 단위. 유효한 조합만 저장, 상품당 최대 500개
CREATE TABLE product_schema.product_option_combinations
(
    id                uuid         NOT NULL DEFAULT gen_random_uuid(),
    product_id        uuid         NOT NULL, -- ref: products.id
    sku               varchar(100),          -- WMS/3PL 연동용. NULL 허용
    combination_key   varchar(500) NOT NULL, -- 옵션값 ID 오름차순 조합 문자열 (예: "3:7:12")
    original_price    integer,               -- 비교 가격(정가). NULL=미설정. 취소선 표시용
    price             integer      NOT NULL, -- 실제 판매가
    stock             integer      NOT NULL DEFAULT 0, -- 총 보유 재고. 가용재고 = stock - reserved_stock
    reserved_stock    integer      NOT NULL DEFAULT 0, -- 예약(잠금) 재고
    is_available      boolean      NOT NULL DEFAULT true, -- 판매 가능 여부 (false=단종)
    search_indexed_at timestamptz,           -- ES 도큐먼트 마지막 인덱싱 일시
    created_at        timestamptz  NOT NULL,
    updated_at        timestamptz  NOT NULL,
    CONSTRAINT pk_product_option_combinations PRIMARY KEY (id),
    CONSTRAINT ck_poc_reserved_stock CHECK (0 <= reserved_stock AND reserved_stock <= stock)
);
CREATE UNIQUE INDEX ON product_schema.product_option_combinations (product_id, combination_key);
CREATE INDEX ON product_schema.product_option_combinations (product_id, stock);
CREATE INDEX ON product_schema.product_option_combinations (product_id, is_available);
CREATE UNIQUE INDEX ON product_schema.product_option_combinations (product_id, sku); -- SKU는 상품 범위 내 유일

COMMENT ON TABLE product_schema.product_option_combinations IS '옵션 조합별 재고·가격·SKU 관리 단위. 유효한 조합만 저장(미생산 omit), 상품당 최대 500개. 결제 직전 가격·재고는 항상 PG 재검증';
COMMENT ON COLUMN product_schema.product_option_combinations.product_id IS 'ref: products.id';
COMMENT ON COLUMN product_schema.product_option_combinations.sku IS 'SKU 코드 (WMS/3PL 연동용). NULL 허용';
COMMENT ON COLUMN product_schema.product_option_combinations.combination_key IS '옵션값 ID 오름차순 조합 문자열 (예: "3:7:12"). 앱이 생성, 중복방지는 unique 인덱스가 강제';
COMMENT ON COLUMN product_schema.product_option_combinations.original_price IS '비교 가격(정가). NULL=미설정. 취소선 표시용';
COMMENT ON COLUMN product_schema.product_option_combinations.price IS '실제 판매가. base_price + Σ(price_delta) + Σ(surcharge_rule.amount)로 산출·저장. 표시·결제가 = COALESCE(combination_winning_discounts.final_price, price) − 라이브 할인액';
COMMENT ON COLUMN product_schema.product_option_combinations.stock IS '총 보유 재고. 가용재고 = stock - reserved_stock. 실차감은 결제 성공 시';
COMMENT ON COLUMN product_schema.product_option_combinations.reserved_stock IS '예약(잠금) 재고. 주문 생성 +qty, 결제 성공 stock·reserved 동시 -qty, 취소·만료 reserved -= qty. CHECK 0<=reserved<=stock';
COMMENT ON COLUMN product_schema.product_option_combinations.is_available IS '판매 가능 여부 (false=단종, stock=0 품절과 구별)';
COMMENT ON COLUMN product_schema.product_option_combinations.search_indexed_at IS 'ES 도큐먼트 마지막 인덱싱 일시';

-- 옵션 조합 ↔ 옵션 값 매핑. 조합 해석 및 역조회 용도
CREATE TABLE product_schema.product_option_combination_values
(
    id                    uuid        NOT NULL DEFAULT gen_random_uuid(),
    option_combination_id uuid        NOT NULL, -- ref: product_option_combinations.id
    option_value_id       uuid        NOT NULL, -- ref: product_option_values.id
    created_at            timestamptz NOT NULL,
    CONSTRAINT pk_product_option_combination_values PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ON product_schema.product_option_combination_values (option_combination_id, option_value_id);
CREATE INDEX ON product_schema.product_option_combination_values (option_value_id);

COMMENT ON TABLE product_schema.product_option_combination_values IS '옵션 조합 ↔ 옵션 값 매핑. 조합 해석 및 역조회 용도';
COMMENT ON COLUMN product_schema.product_option_combination_values.option_combination_id IS 'ref: product_option_combinations.id';
COMMENT ON COLUMN product_schema.product_option_combination_values.option_value_id IS 'ref: product_option_values.id';

-- 상품별 옵션 저작 룰(조합 추가금 + 불가 조합) 통합 보관 (1:1)
CREATE TABLE product_schema.product_option_configs
(
    product_id      uuid        NOT NULL, -- PK이자 ref: products.id (1:1)
    surcharge_rules jsonb,                -- 조합 추가금 룰 [{"valueIds":["uuid",...],"amount":50000}]
    exclusion_rules jsonb,                -- 불가 조합 룰 [{"valueIds":["uuid",...],"reason":"..."}]
    created_at      timestamptz NOT NULL,
    updated_at      timestamptz NOT NULL,
    CONSTRAINT pk_product_option_configs PRIMARY KEY (product_id)
);

COMMENT ON TABLE product_schema.product_option_configs IS '상품별 옵션 저작 룰(조합 추가금 + 불가 조합) 통합 보관. products 핫 원장 미오염. 런타임은 combination에 가격·행존재로 materialize되어 본 테이블 미참조';
COMMENT ON COLUMN product_schema.product_option_configs.product_id IS 'PK이자 ref: products.id (1:1). 옵션 저작 룰 전용 — 편집 왕복·조합 재생성 때만 로드';
COMMENT ON COLUMN product_schema.product_option_configs.surcharge_rules IS '조합 추가금 룰 [{"valueIds":["uuid",...],"amount":50000}]. 부분조건(valueIds 전부 포함) 매칭 조합에 amount 가산';
COMMENT ON COLUMN product_schema.product_option_configs.exclusion_rules IS '불가 조합 룰 [{"valueIds":["uuid",...],"reason":"..."}]. 매칭 조합은 생성 시 행 미생성';

-- 주문 이전 단계(체크아웃·라이브 플래시) 재고 선예약 원장
CREATE TABLE product_schema.stock_reservations
(
    id             uuid        NOT NULL DEFAULT gen_random_uuid(),
    combination_id uuid        NOT NULL, -- ref: product_option_combinations.id
    reserved_by    uuid,                 -- ref: users.id. 예약 주체. 비회원은 NULL + session_id
    session_id     varchar(100),         -- 비회원 홀드 트래킹
    order_item_id  uuid,                 -- ref: order_items.id. 주문 전환 시 연결. 주문前 홀드는 NULL
    quantity       integer     NOT NULL, -- 예약 수량
    status         varchar(15) NOT NULL DEFAULT 'HELD', -- ENUM: HELD, COMMITTED, RELEASED, EXPIRED
    expires_at     timestamptz NOT NULL, -- 홀드 만료 일시. 배치/Redis TTL 회수
    created_at     timestamptz NOT NULL,
    updated_at     timestamptz NOT NULL,
    CONSTRAINT pk_stock_reservations PRIMARY KEY (id)
);
CREATE INDEX ON product_schema.stock_reservations (combination_id, status);
CREATE INDEX ON product_schema.stock_reservations (expires_at) WHERE status = 'HELD'; -- 만료 회수 배치
CREATE INDEX ON product_schema.stock_reservations (reserved_by, status);
CREATE INDEX ON product_schema.stock_reservations (order_item_id);

COMMENT ON TABLE product_schema.stock_reservations IS '주문 이전 단계(체크아웃·라이브 플래시) 재고 선예약 원장. 일반 주문은 order_items가 예약 원장이라 미사용 — 본 테이블은 주문前 홀드(Redis 선예약의 durable 미러) 전용. combination.reserved_stock은 HELD quantity 집계 캐시';
COMMENT ON COLUMN product_schema.stock_reservations.combination_id IS 'ref: product_option_combinations.id';
COMMENT ON COLUMN product_schema.stock_reservations.reserved_by IS 'ref: users.id. 예약 주체. 비회원은 NULL + session_id';
COMMENT ON COLUMN product_schema.stock_reservations.session_id IS '비회원 홀드 트래킹';
COMMENT ON COLUMN product_schema.stock_reservations.order_item_id IS 'ref: order_items.id. 주문 전환 시 연결. 주문前 홀드는 NULL';
COMMENT ON COLUMN product_schema.stock_reservations.quantity IS '예약 수량';
COMMENT ON COLUMN product_schema.stock_reservations.status IS 'ENUM: HELD, COMMITTED, RELEASED, EXPIRED';
COMMENT ON COLUMN product_schema.stock_reservations.expires_at IS '홀드 만료 일시. 배치/Redis TTL 회수';

-- ============================================================
-- §6  기간 할인 정책 + 승자 캐시
-- ============================================================

-- 기간·상시 할인 정책. 조합별 승자 1개 선정(write-time resolution)
CREATE TABLE product_schema.discount_policies
(
    id             uuid         NOT NULL DEFAULT gen_random_uuid(),
    name           varchar(100) NOT NULL,
    description    text,
    discount_type  varchar(15)  NOT NULL, -- ENUM: RATE, FIXED_AMOUNT
    discount_value integer      NOT NULL, -- RATE=할인율(%), FIXED_AMOUNT=할인 금액(원)
    priority       integer      NOT NULL DEFAULT 0, -- 높을수록 우선. 할인액 무관 override. 프로모션=높은 값(예 100)
    started_at     timestamptz,           -- NULL=즉시 적용
    ended_at       timestamptz,           -- NULL=상시
    is_active      boolean      NOT NULL DEFAULT true,
    created_by     uuid         NOT NULL, -- ref: users.id (role=ADMIN)
    created_at     timestamptz  NOT NULL,
    updated_at     timestamptz  NOT NULL,
    CONSTRAINT pk_discount_policies PRIMARY KEY (id)
);
CREATE INDEX ON product_schema.discount_policies (is_active, started_at, ended_at);
CREATE INDEX ON product_schema.discount_policies (is_active, created_at);

COMMENT ON TABLE product_schema.discount_policies IS '기간·상시 할인 정책. 적용 조건: is_active=1 AND 기간 충족. 승자 선정 순서: ① priority DESC → ② 타깃 구체성(조합>상품) → ③ 할인액 DESC → ④ policy_id DESC';
COMMENT ON COLUMN product_schema.discount_policies.discount_type IS 'ENUM: RATE, FIXED_AMOUNT';
COMMENT ON COLUMN product_schema.discount_policies.discount_value IS '할인값. RATE=할인율(%), FIXED_AMOUNT=할인 금액(원)';
COMMENT ON COLUMN product_schema.discount_policies.priority IS '우선순위. 높을수록 우선. 할인액과 무관하게 상위 priority가 override. 프로모션=높은 값(예 100). 0=일반 정책';
COMMENT ON COLUMN product_schema.discount_policies.started_at IS '할인 시작 일시. NULL=즉시 적용';
COMMENT ON COLUMN product_schema.discount_policies.ended_at IS '할인 종료 일시. NULL=상시';
COMMENT ON COLUMN product_schema.discount_policies.created_by IS 'ref: users.id (role=ADMIN)';

-- 할인 정책 ↔ 상품 매핑 (product-level)
CREATE TABLE product_schema.discount_policy_products
(
    id                 uuid        NOT NULL DEFAULT gen_random_uuid(),
    discount_policy_id uuid        NOT NULL, -- ref: discount_policies.id
    product_id         uuid        NOT NULL, -- ref: products.id
    created_at         timestamptz NOT NULL,
    CONSTRAINT pk_discount_policy_products PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ON product_schema.discount_policy_products (discount_policy_id, product_id);
CREATE INDEX ON product_schema.discount_policy_products (product_id);

COMMENT ON TABLE product_schema.discount_policy_products IS '할인 정책 ↔ 상품 매핑 (product-level). 해당 상품 모든 조합에 기본 적용. 승자는 combination_winning_discounts에 write-time 저장';
COMMENT ON COLUMN product_schema.discount_policy_products.discount_policy_id IS 'ref: discount_policies.id';
COMMENT ON COLUMN product_schema.discount_policy_products.product_id IS 'ref: products.id';

-- 할인 정책 ↔ 조합 매핑 (combination-level, product-level보다 우선)
CREATE TABLE product_schema.discount_policy_combinations
(
    id                 uuid        NOT NULL DEFAULT gen_random_uuid(),
    discount_policy_id uuid        NOT NULL, -- ref: discount_policies.id
    combination_id     uuid        NOT NULL, -- ref: product_option_combinations.id
    created_at         timestamptz NOT NULL,
    CONSTRAINT pk_discount_policy_combinations PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ON product_schema.discount_policy_combinations (discount_policy_id, combination_id);
CREATE INDEX ON product_schema.discount_policy_combinations (combination_id);

COMMENT ON TABLE product_schema.discount_policy_combinations IS '할인 정책 ↔ 조합 매핑 (combination-level). 동일 priority 내에서 product-level보다 우선(override). priority가 다르면 priority가 우선';
COMMENT ON COLUMN product_schema.discount_policy_combinations.discount_policy_id IS 'ref: discount_policies.id';
COMMENT ON COLUMN product_schema.discount_policy_combinations.combination_id IS 'ref: product_option_combinations.id';

-- 조합당 현재 승자 할인 1개 저장(파생 캐시). 행 없음=할인 없음
CREATE TABLE product_schema.combination_winning_discounts
(
    combination_id  uuid        NOT NULL, -- PK이자 ref: product_option_combinations.id (1:1)
    policy_id       uuid        NOT NULL, -- ref: discount_policies.id. 현재 승자 정책
    discount_amount integer     NOT NULL, -- 승자 정책 할인 금액(원)
    final_price     integer     NOT NULL, -- 할인 후 최종 가격 = price - discount_amount
    resolved_at     timestamptz NOT NULL, -- 마지막 재계산 일시
    CONSTRAINT pk_combination_winning_discounts PRIMARY KEY (combination_id)
);

COMMENT ON TABLE product_schema.combination_winning_discounts IS '조합당 현재 승자 할인 1개 저장(파생 캐시). 행 없음=할인 없음. 승자 선정: priority DESC → 조합-레벨>상품-레벨 → 할인액 DESC → policy_id DESC. 정합성은 앱이 정책 변경 시 유지';
COMMENT ON COLUMN product_schema.combination_winning_discounts.combination_id IS 'PK이자 ref: product_option_combinations.id (1:1). 할인 적용 조합만 행 존재';
COMMENT ON COLUMN product_schema.combination_winning_discounts.policy_id IS 'ref: discount_policies.id. 현재 승자 정책';
COMMENT ON COLUMN product_schema.combination_winning_discounts.discount_amount IS '승자 정책 할인 금액(원). RATE: ROUND(price×rate/100) / FIXED_AMOUNT: LEAST(value, price)';
COMMENT ON COLUMN product_schema.combination_winning_discounts.final_price IS '할인 후 최종 가격 = price - discount_amount';
COMMENT ON COLUMN product_schema.combination_winning_discounts.resolved_at IS '마지막 재계산 일시. stale 모니터링 기준';

-- ============================================================
-- §13  상품 Q&A (구매 전 문의)
-- ============================================================

-- 상품 문의 (Q&A). 비밀글 지원, 판매자 전용 답변
CREATE TABLE product_schema.product_faq
(
    id             uuid         NOT NULL DEFAULT gen_random_uuid(),
    product_id     uuid         NOT NULL, -- ref: products.id
    user_id        uuid         NOT NULL, -- ref: users.id (문의 작성자)
    inquiry_type   varchar(30)  NOT NULL, -- ENUM: PRODUCT, DELIVERY, EXCHANGE, REFUND, ETC
    title          varchar(255) NOT NULL,
    content        text         NOT NULL,
    is_private     boolean      NOT NULL DEFAULT false,
    status         varchar(20)  NOT NULL DEFAULT 'WAITING', -- ENUM: WAITING, ANSWERED
    answer_content text,
    answered_by    uuid,                  -- ref: users.id (답변자: 판매자 전용)
    answered_at    timestamptz,
    deleted_at     timestamptz,           -- 논리 삭제 일시
    created_at     timestamptz  NOT NULL,
    updated_at     timestamptz  NOT NULL,
    CONSTRAINT pk_product_faq PRIMARY KEY (id)
);
CREATE INDEX ON product_schema.product_faq (product_id, status, created_at);
CREATE INDEX ON product_schema.product_faq (user_id, created_at);
CREATE INDEX ON product_schema.product_faq (answered_by);

COMMENT ON TABLE product_schema.product_faq IS '상품 문의 (Q&A). 비밀글 지원, 판매자 전용 답변';
COMMENT ON COLUMN product_schema.product_faq.product_id IS 'ref: products.id';
COMMENT ON COLUMN product_schema.product_faq.user_id IS 'ref: users.id (문의 작성자)';
COMMENT ON COLUMN product_schema.product_faq.inquiry_type IS 'ENUM: PRODUCT, DELIVERY, EXCHANGE, REFUND, ETC';
COMMENT ON COLUMN product_schema.product_faq.is_private IS '비밀글 여부';
COMMENT ON COLUMN product_schema.product_faq.status IS 'ENUM: WAITING, ANSWERED. 삭제는 deleted_at으로 처리';
COMMENT ON COLUMN product_schema.product_faq.answered_by IS 'ref: users.id (답변자: 판매자 전용)';
COMMENT ON COLUMN product_schema.product_faq.deleted_at IS '논리 삭제 일시';

-- 상품 문의 첨부 이미지
CREATE TABLE product_schema.product_inquiry_images
(
    id               uuid         NOT NULL DEFAULT gen_random_uuid(),
    inquiry_id       uuid         NOT NULL, -- ref: product_faq.id
    image_key        varchar(500) NOT NULL,
    origin_file_name varchar(255),
    sort_order       integer      NOT NULL DEFAULT 0,
    deleted_at       timestamptz,           -- 논리 삭제 일시
    created_at       timestamptz  NOT NULL,
    CONSTRAINT pk_product_inquiry_images PRIMARY KEY (id)
);
CREATE INDEX ON product_schema.product_inquiry_images (inquiry_id, sort_order);

COMMENT ON TABLE product_schema.product_inquiry_images IS '상품 문의 첨부 이미지';
COMMENT ON COLUMN product_schema.product_inquiry_images.inquiry_id IS 'ref: product_faq.id';
COMMENT ON COLUMN product_schema.product_inquiry_images.image_key IS '스토리지 키';
COMMENT ON COLUMN product_schema.product_inquiry_images.origin_file_name IS '원본 파일명';
COMMENT ON COLUMN product_schema.product_inquiry_images.deleted_at IS '논리 삭제 일시';

-- ============================================================
-- §19  운영 (베스트 · 감사 로그)
-- ============================================================

-- 주간 베스트 상품. 판매량·금액 기준 최대 30위 (배치 생성)
CREATE TABLE product_schema.weekly_best_products
(
    id           uuid        NOT NULL DEFAULT gen_random_uuid(),
    week_start   date        NOT NULL, -- 집계 기준 주 시작일 (월요일)
    rank         smallint    NOT NULL, -- 순위 (1~30)
    product_id   uuid        NOT NULL, -- ref: products.id
    sales_count  integer     NOT NULL, -- 해당 주 판매 수량
    sales_amount integer     NOT NULL, -- 해당 주 판매 금액 합계 (원)
    created_at   timestamptz NOT NULL,
    CONSTRAINT pk_weekly_best_products PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ON product_schema.weekly_best_products (week_start, rank);

COMMENT ON TABLE product_schema.weekly_best_products IS '주간 베스트 상품. 판매량·금액 기준 최대 30위 (배치 생성)';
COMMENT ON COLUMN product_schema.weekly_best_products.week_start IS '집계 기준 주 시작일 (월요일)';
COMMENT ON COLUMN product_schema.weekly_best_products.rank IS '순위 (1~30)';
COMMENT ON COLUMN product_schema.weekly_best_products.product_id IS 'ref: products.id';
COMMENT ON COLUMN product_schema.weekly_best_products.sales_count IS '해당 주 판매 수량';
COMMENT ON COLUMN product_schema.weekly_best_products.sales_amount IS '해당 주 판매 금액 합계 (원)';

-- 주요 행위 감사 로그. 행위자·대상 리소스·IP 기록
CREATE TABLE product_schema.audit_logs
(
    id          uuid         NOT NULL DEFAULT gen_random_uuid(),
    actor_id    uuid,                     -- 행위자 ID (users.id — role로 구분). SYSTEM이면 NULL
    actor_type  varchar(10)  NOT NULL,    -- ENUM: USER, ADMIN, SYSTEM
    action      varchar(100) NOT NULL,    -- 행위 코드 (예: PAYMENT_COMPLETE)
    target_id   uuid,                     -- 대상 리소스 ID
    target_type varchar(50),              -- 대상 리소스 타입
    detail      jsonb,                    -- 변경 전후 데이터 등 상세
    ip_address  varchar(45),              -- 요청 IP
    created_at  timestamptz  NOT NULL,
    CONSTRAINT pk_product_audit_logs PRIMARY KEY (id)
);
CREATE INDEX ON product_schema.audit_logs (actor_id, actor_type, created_at);
CREATE INDEX ON product_schema.audit_logs (action, created_at);

COMMENT ON TABLE product_schema.audit_logs IS '주요 행위 감사 로그. 행위자·대상 리소스·IP 기록';
COMMENT ON COLUMN product_schema.audit_logs.actor_id IS '행위자 ID (users.id — role로 구분). SYSTEM이면 NULL';
COMMENT ON COLUMN product_schema.audit_logs.actor_type IS 'ENUM: USER, ADMIN, SYSTEM';
COMMENT ON COLUMN product_schema.audit_logs.action IS '행위 코드 (예: PAYMENT_COMPLETE)';
COMMENT ON COLUMN product_schema.audit_logs.target_id IS '대상 리소스 ID';
COMMENT ON COLUMN product_schema.audit_logs.target_type IS '대상 리소스 타입';
COMMENT ON COLUMN product_schema.audit_logs.detail IS '변경 전후 데이터 등 상세';
COMMENT ON COLUMN product_schema.audit_logs.ip_address IS '요청 IP';

-- ============================================================
-- §20  검색 로그 (비파티션 — 월별 RANGE 파티셔닝은 운영 단계에서 적용)
-- ============================================================

-- 검색 로그. 직접 INSERT 금지 — Redis/Kafka 버퍼링 후 bulk COPY
CREATE TABLE product_schema.product_search_logs
(
    id                     bigint       NOT NULL, -- 앱 생성 TSID (serial 미사용)
    keyword                varchar(200) NOT NULL, -- 검색어 (원문, 정규화는 ES 담당)
    user_id                uuid,                  -- users.id (FK 미설정). NULL=비로그인
    session_id             varchar(100),          -- 비로그인 트래킹용 세션 ID
    result_count           integer      NOT NULL DEFAULT 0, -- ES 검색 결과 수. 0=노결과
    clicked_product_id     uuid,                  -- products.id (FK 미설정). NULL=클릭 없이 이탈
    clicked_combination_id uuid,                  -- product_option_combinations.id (FK 미설정)
    searched_at            timestamptz  NOT NULL, -- 검색 일시
    CONSTRAINT pk_product_search_logs PRIMARY KEY (id)
);
CREATE INDEX ON product_schema.product_search_logs USING BRIN (searched_at); -- 시계열 append
CREATE INDEX ON product_schema.product_search_logs (keyword, searched_at);
CREATE INDEX ON product_schema.product_search_logs (user_id, searched_at) WHERE user_id IS NOT NULL;
CREATE INDEX ON product_schema.product_search_logs (clicked_product_id, searched_at) WHERE clicked_product_id IS NOT NULL;

COMMENT ON TABLE product_schema.product_search_logs IS '검색 로그. 하루 5~8M rows. 직접 INSERT 금지 — Redis/Kafka 버퍼링 후 bulk COPY. 대시보드 집계는 search_keyword_daily_stats 사용. (월별 RANGE 파티셔닝은 운영 단계에서 적용)';
COMMENT ON COLUMN product_schema.product_search_logs.id IS '앱 생성 TSID — 배치 COPY 호환(auto increment 미사용)';
COMMENT ON COLUMN product_schema.product_search_logs.keyword IS '검색어 (원문, 정규화는 ES 담당)';
COMMENT ON COLUMN product_schema.product_search_logs.user_id IS 'users.id (FK 미설정 — 대용량 로그 INSERT 비용 회피). NULL=비로그인';
COMMENT ON COLUMN product_schema.product_search_logs.session_id IS '비로그인 트래킹용 세션 ID';
COMMENT ON COLUMN product_schema.product_search_logs.result_count IS 'ES 검색 결과 수. 0=노결과';
COMMENT ON COLUMN product_schema.product_search_logs.clicked_product_id IS 'products.id (FK 미설정). NULL=클릭 없이 이탈';
COMMENT ON COLUMN product_schema.product_search_logs.clicked_combination_id IS 'product_option_combinations.id (FK 미설정). pre-select 연동용';
COMMENT ON COLUMN product_schema.product_search_logs.searched_at IS '검색 일시';

-- 검색어 일별 집계 (야간 배치). seller 대시보드 검색어 쿼리 소스
CREATE TABLE product_schema.search_keyword_daily_stats
(
    id           bigint       NOT NULL, -- 앱 생성 TSID (serial 미사용)
    date         date         NOT NULL, -- 집계 기준일
    keyword      varchar(200) NOT NULL,
    seller_id    uuid,                  -- ref: users.id (role=SELLER). NULL=플랫폼 전체
    product_id   uuid,                  -- ref: products.id. NULL=키워드 단위 집계
    search_count integer      NOT NULL DEFAULT 0,
    click_count  integer      NOT NULL DEFAULT 0, -- CTR = click_count / search_count
    CONSTRAINT pk_search_keyword_daily_stats PRIMARY KEY (id)
);
-- 배치 재실행 업서트 멱등 키 (NULLS NOT DISTINCT — PG15+)
CREATE UNIQUE INDEX ON product_schema.search_keyword_daily_stats (date, keyword, seller_id, product_id) NULLS NOT DISTINCT;
CREATE INDEX ON product_schema.search_keyword_daily_stats (date, seller_id, search_count);
CREATE INDEX ON product_schema.search_keyword_daily_stats (date, keyword, search_count);
CREATE INDEX ON product_schema.search_keyword_daily_stats (date, product_id, click_count) WHERE product_id IS NOT NULL;

COMMENT ON TABLE product_schema.search_keyword_daily_stats IS '[야간 배치 집계] product_search_logs를 날짜·키워드·판매자·상품 단위로 집계. seller 대시보드 검색어 쿼리 소스. (월별 RANGE 파티셔닝은 운영 단계에서 적용)';
COMMENT ON COLUMN product_schema.search_keyword_daily_stats.id IS '앱 생성 TSID — 배치 INSERT 호환(auto increment 미사용)';
COMMENT ON COLUMN product_schema.search_keyword_daily_stats.date IS '집계 기준일';
COMMENT ON COLUMN product_schema.search_keyword_daily_stats.seller_id IS 'ref: users.id (role=SELLER). NULL=플랫폼 전체';
COMMENT ON COLUMN product_schema.search_keyword_daily_stats.product_id IS 'ref: products.id. NULL=키워드 단위 집계';
COMMENT ON COLUMN product_schema.search_keyword_daily_stats.search_count IS '검색 횟수';
COMMENT ON COLUMN product_schema.search_keyword_daily_stats.click_count IS '클릭 횟수 (CTR = click_count / search_count)';

-- ============================================================
-- §31  Outbox 이벤트 (PG ↔ ES 비동기 동기화)
-- ============================================================

-- Transactional Outbox. 비즈니스 INSERT와 같은 트랜잭션에서 INSERT → 워커가 폴링하여 ES 반영
CREATE TABLE product_schema.outbox_events
(
    id             bigint      NOT NULL, -- 앱 생성 TSID (시간순 단조 증가, auto increment 미사용)
    aggregate_type varchar(50) NOT NULL, -- ENUM: product, combination, order, review
    aggregate_id   uuid        NOT NULL, -- 도메인 객체 ID. FK 미설정 — 삭제 후에도 발행 가능
    event_type     varchar(50) NOT NULL, -- ENUM: UPSERTED, DELETED, STOCK_CHANGED, PRICE_CHANGED, DISCOUNT_WINNER_CHANGED, REVIEW_ADDED, OPTION_VALUE_RENAMED
    payload        jsonb       NOT NULL, -- 이벤트 페이로드
    created_at     timestamptz NOT NULL DEFAULT now(),
    processed_at   timestamptz,          -- 워커 처리 완료 일시. NULL=미처리. 완료 7일 후 삭제
    retry_count    integer     NOT NULL DEFAULT 0, -- 재시도 횟수. 3 이상이면 Dead Letter
    last_error     text,                 -- 마지막 실패 사유. 성공 시 NULL
    CONSTRAINT pk_product_outbox_events PRIMARY KEY (id),
    CONSTRAINT ck_outbox_retry_count CHECK (retry_count >= 0)
);
CREATE INDEX ON product_schema.outbox_events (created_at) WHERE processed_at IS NULL;       -- 워커 폴링 큐
CREATE INDEX ON product_schema.outbox_events (aggregate_type, aggregate_id);
CREATE INDEX ON product_schema.outbox_events (event_type, created_at);
CREATE INDEX ON product_schema.outbox_events (retry_count, created_at) WHERE retry_count > 0; -- 재시도 우선순위

COMMENT ON TABLE product_schema.outbox_events IS 'Transactional Outbox — PG ↔ ES 비동기 동기화 원자성 보장. 비즈니스 INSERT와 같은 트랜잭션에서 INSERT → 별도 워커가 폴링하여 ES 반영';
COMMENT ON COLUMN product_schema.outbox_events.id IS 'PK — 앱 생성 TSID(시간순 단조 증가, auto increment 미사용)';
COMMENT ON COLUMN product_schema.outbox_events.aggregate_type IS 'ENUM: product, combination, order, review';
COMMENT ON COLUMN product_schema.outbox_events.aggregate_id IS '도메인 객체 ID. FK 미설정 — 삭제 후에도 발행 가능';
COMMENT ON COLUMN product_schema.outbox_events.event_type IS 'ENUM: UPSERTED, DELETED, STOCK_CHANGED, PRICE_CHANGED, DISCOUNT_WINNER_CHANGED, REVIEW_ADDED, OPTION_VALUE_RENAMED';
COMMENT ON COLUMN product_schema.outbox_events.payload IS '이벤트 페이로드. ES 인덱싱에 필요한 데이터 포함';
COMMENT ON COLUMN product_schema.outbox_events.processed_at IS '워커 처리 완료 일시. NULL=미처리. 완료 7일 후 삭제';
COMMENT ON COLUMN product_schema.outbox_events.retry_count IS '재시도 횟수. 3 이상이면 Dead Letter';
COMMENT ON COLUMN product_schema.outbox_events.last_error IS '마지막 실패 사유. 성공 시 NULL';
