plugins {
    id 'java-library'
}

dependencies {
    implementation project(':common:web')
    implementation project(':storage:redis-core')

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

tasks.register("prepareKotlinBuildScriptModel"){}
