dependencies {
    implementation project(':common:web')
    implementation project(':common:auth')
    implementation(project(":modules:customer:customer-api"))
    implementation(project(":modules:customer:customer-core"))
    implementation(project(":modules:seller:seller-api"))
    implementation(project(":modules:seller:seller-core"))
    implementation(project(":modules:notification:notification-core"))
    implementation(project(":modules:user:user-core"))
    implementation(project(":storage:redis-core"))
    implementation(project(":storage:object-storage"))

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.bouncycastle:bcprov-jdk18on:1.84'

    runtimeOnly("org.postgresql:postgresql")

    testImplementation "com.navercorp.fixturemonkey:fixture-monkey-starter:1.1.19"
    testImplementation 'org.springframework.boot:spring-boot-webmvc-test'
    testImplementation 'org.springframework.security:spring-security-test'
}

tasks.register("prepareKotlinBuildScriptModel"){}

bootJar {
    enabled = true
}

jar{
    enabled = false
}
